// HTML element names for the prototype UI.
elements = {
    idField: "id-field",
    searchForm: "search-form",
    isPlaylist: "is-playlist",
    submitLoader: "submit-loader",
    previewContainer: "preview-container",
    thumbnailImage: "thumbnail-image",
    videoTitle: "video-title",
    analyzeButton: "analyze-button",
    analyzeLoader: "analyze-loader",
    analysisSection: "analysis-section",
    listPane: "list-pane",
    playlistEntries: "playlist-entries",
    analysisPane: "analysis-pane",
    analysisTitle: "analysis-title",
    analysisIframe: "analysis-iframe",
    happyMeter: "happy-meter",
    analysisSearch: "analysis-search",
    topButton: "top-button",
}